SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO 
WHERE ITEM_ID IN (
    SELECT IT.ITEM_ID
    FROM ITEM_INFO II, ITEM_TREE IT
    WHERE II.ITEM_ID = IT.PARENT_ITEM_ID AND II.RARITY = 'RARE'
)
ORDER BY ITEM_ID DESC;
